version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/bikebike/backend
    ports:
      - "3001:3000"
    depends_on:
      - db
  bikebike:
    image: "node:10-alpine"
    user: "node"
    working_dir: /bikebike/bikebike
    volumes:
      - ./bikebike:/bikebike/bikebike
    ports:
      - "3000:3000"
    command: "yarn start"
    depends_on:
      - backend
